language: python
virtualenv:
  # This allows installing PyQt using apt-get and being able to import it.
  system_site_packages: true
# command to install dependencies
install: 
  - sudo apt-get install python-qt4 python-qt4-dev pyqt4-dev-tools
  - pip install -r requirements.txt
  - python setup.py install
# command to run tests
script:
  - python run_tests.py