language: python
virtualenv:
  # This allows installing PyQt using apt-get and being able to import it.
  system_site_packages: true
# command to install dependencies
install: 
  - sudo apt-get install python-qt4 python-qt4-dev
  - "pip install -r requirements.txt"
# command to run tests
script:
  - python tests/test_all.py